### ISSUE TITLE
Bundle error when running

### ISSUE THREAD

**Issue by cheshire137** [millidavids/chore-calendar#3]
With a fresh `docker-compose up`, I get this output:

```
db_1     | LOG:  autovacuum launcher started
chore_1  | /usr/local/bundle/gems/bundler-1.7.12/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find byebug-6.0.2 in any of the sources (Bundler::GemNotFound)
chore_1  |  from /usr/local/bundle/gems/bundler-1.7.12/lib/bundler/spec_set.rb:85:in `map!'
chore_1  |  from /usr/local/bundle/gems/bundler-1.7.12/lib/bundler/spec_set.rb:85:in `materialize'
chore_1  |  from /usr/local/bundle/gems/bundler-1.7.12/lib/bundler/definition.rb:132:in `specs'
chore_1  |  from /usr/local/bundle/gems/bundler-1.7.12/lib/bundler/definition.rb:177:in `specs_for'
chore_1  |  from /usr/local/bundle/gems/bundler-1.7.12/lib/bundler/definition.rb:166:in `requested_specs'
chore_1  |  from /usr/local/bundle/gems/bundler-1.7.12/lib/bundler/environment.rb:18:in `requested_specs'
chore_1  |  from /usr/local/bundle/gems/bundler-1.7.12/lib/bundler/runtime.rb:13:in `setup'
chore_1  |  from /usr/local/bundle/gems/bundler-1.7.12/lib/bundler.rb:122:in `setup'
chore_1  |  from /usr/local/bundle/gems/bundler-1.7.12/lib/bundler/setup.rb:17:in `<top (required)>'
chore_1  |  from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
chore_1  |  from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
chorecalendar_chore_1 exited with code 1
db_1     |  done
db_1     | server started
```

Nothing is running on my host at 192.168.99.100:3000.

**Comment by summasmiff** [comment]
I hit this. I think it's bundler trying to install a dependency before it installs another thing. Running bundle install inside my docker container fixed it.
